#durid数据库连接池设置
spring:
  profiles:
    ##此处引入配置其他数据源配置文件
    include: dev-datasource
  aop:
    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:postgresql://192.168.5.112:5432/zzjgkf
#    url: jdbc:oracle:thin:@//113.125.201.130:11523/orcl
#    username: sy_dmbzb_newkf
#    password: sy_dmbzb_newkf
    url: jdbc:oracle:thin:@//113.125.201.130:11524/orcl
    username: sy_dmbzb_cs
    password: shineyue2020
#    url: jdbc:oracle:thin:@//113.125.201.130:11524/orcl
#    username: sy_dmbzb_zj
#    password: sy_dmbzb_zj
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 1
    maxActive: 15
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000